In [27]:
import numpy as np
import pandas as pd
import math
from sklearn.naive_bayes import MultinomialNB


def LoadData(filename):
    data = pd.read_excel(filename, header=None)
    dataval = data.values
    return dataval

In [108]:
X = LoadData("data/X.xlsx")
y = LoadData("data/y.xlsx").reshape(-1)
Xt = LoadData("data/X_test.xlsx")
yt = LoadData("data/y_test.xlsx").reshape(-1)
print(X.shape)
print(y.shape)
print(Xt.shape)
print(yt.shape)

(22, 3)
(22,)
(23, 3)
(23,)


In [122]:
from sklearn.naive_bayes import MultinomialNB
MB = MultinomialNB()
MB.fit_prior=False
print(MB)
MB.fit(X, y)
print(MB.score(X,y))
print(X.T)
print(y)
print(MB.predict(X))
print()
print(Xt.T)
print(MB.predict(Xt))
print(yt)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=False)
0.5454545454545454
[[1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 3 3 3 4]
 [1 1 1 1 2 2 2 2 3 3 4 2 2 2 3 3 4 4 3 3 4 4]
 [1 2 3 4 1 2 3 4 3 4 4 2 3 4 3 4 1 4 3 4 4 4]]
[1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 4]
[4 1 1 1 3 2 2 1 2 2 2 4 3 1 3 2 4 2 4 3 3 4]

[[1 1 1 1 1 1 1 2 2 2 1 1 1 1 2 2 2 2 3 3 3 4 2]
 [1 1 1 1 2 2 2 2 2 2 2 3 3 4 3 3 4 4 3 3 4 4 4]
 [4 2 3 4 1 2 3 2 3 4 4 3 4 4 3 4 1 4 3 4 4 4 4]]
[1 1 1 1 3 2 2 4 3 1 1 2 2 2 3 2 4 2 4 3 3 4 2]
[1 1 1 1 1 2 3 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [110]:
from sklearn.naive_bayes import ComplementNB
CB = ComplementNB()
CB.fit(X, y)
print(CB.score(X,y))
print(X.T)
print(y)
print(CB.predict(X))
print()
print(Xt.T)
print(CB.predict(Xt))
print(yt)

0.6818181818181818
[[1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 3 3 3 4]
 [1 1 1 1 2 2 2 2 3 3 4 2 2 2 3 3 4 4 3 3 4 4]
 [1 2 3 4 1 2 3 4 3 4 4 2 3 4 3 4 1 4 3 4 4 4]]
[1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 4]
[3 1 1 1 3 2 2 2 2 2 2 3 3 1 3 2 3 2 3 3 3 3]

[[1 1 1 1 1 1 1 2 2 2 1 1 1 1 2 2 2 2 3 3 3 4 2]
 [1 1 1 1 2 2 2 2 2 2 2 3 3 4 3 3 4 4 3 3 4 4 4]
 [4 2 3 4 1 2 3 2 3 4 4 3 4 4 3 4 1 4 3 4 4 4 4]]
[1 1 1 1 3 2 2 3 3 1 2 2 2 2 3 2 3 2 3 3 3 3 2]
[1 1 1 1 1 2 3 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [111]:
from sklearn.naive_bayes import GaussianNB
GB = GaussianNB()
GB.fit(X, y)
print(GB.score(X,y))
print(X.T)
print(y)
print(GB.predict(X))
print()
print(Xt.T)
print(GB.predict(Xt))
print(yt)

0.9545454545454546
[[1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 3 3 3 4]
 [1 1 1 1 2 2 2 2 3 3 4 2 2 2 3 3 4 4 3 3 4 4]
 [1 2 3 4 1 2 3 4 3 4 4 2 3 4 3 4 1 4 3 4 4 4]]
[1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 4]
[1 1 1 1 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4]

[[1 1 1 1 1 1 1 2 2 2 1 1 1 1 2 2 2 2 3 3 3 4 2]
 [1 1 1 1 2 2 2 2 2 2 2 3 3 4 3 3 4 4 3 3 4 4 4]
 [4 2 3 4 1 2 3 2 3 4 4 3 4 4 3 4 1 4 3 4 4 4 4]]
[1 1 1 1 2 2 2 3 3 3 2 2 2 2 3 3 3 3 3 3 3 4 3]
[1 1 1 1 1 2 3 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3]
